undoio/l3

.github/workflows/build.yml
Makefile
include/l3.h
src/l3.c
test.sh

This commit refactors the Makefile rules to ease the addition of rules to integrate Line-of-Code (LOC) package in a follow-on commit. Several redundant TEST_*BIN* etc. symbols are purged.
Existing capabilities are unchanged, and we now additionally support:
```
$ make clean && CC=g++ CXX=g++ LD=g++ make all
$ make run-tests
```
... to build all .c, .cpp and .cc sample-programs and run them in one-pass.
Added `test.sh` wrapper script for devs to quickly re-run all the tests that are run in CI, for easily stabilizing changes w/o having to go thru CI.
----
```
agurajada-Linux-Vm:[1559] $ make help
Usage:
To build all sample programs and run all unit-tests:
make clean && CC=g++ CXX=g++ LD=g++ make all
make run-tests
Alternatively, you may use multiple invocations in this sequence to build all …
```

[Build] Rework Makefile rules to ease addition of LOC package

---

.github/workflows/build.yml
Docs/build.md
Makefile
README.md
l3_dump.py
test.sh

This commit leverages the LOC-generated LOC-decoder binary to unpack the loc_t LOC_ID value stashed away in L3 diag data files. This will be enabled under the `L3_LOC_ENABLED=1`env-var, which is need to integrate L3 with the LOC package
and to re-build the library and sample programs.
Functionally, `l3_dump.py` will trigger the LOC-decoder binary to unpack the LOC-ID, if found, and will report the file-name / line# pair where the l3-logging API was invoked. 
This scheme is supported uniformly for .c, .cpp and .cc files.
Sample output:
----
```
tid=170657 single-file-C-program/test-main.c:85  'Simple-log-msg-Args(1,2)' arg1=1 arg2=2
tid=170657 single-file-C-program/test-main.c:86  'Potential memory overwrite (addr, size)' arg1=3735927486 arg2=1024
tid=170657 …
```

Invoke LOC's unpacking logic on L3 generated logs with L3_LOC_ENABLED=1 runs.

---

Makefile
include/l3.h
l3.S
src/l3.c
tests/unit/l3_dump.py-test.c
use-cases/single-file-C-program/test-main.c
use-cases/single-file-CC-program/test-main.cc
use-cases/single-file-Cpp-program/test-main.cpp

This commit extends fast-logging interfaces, implemented by assembly code, to:
- Support recording 2 args as part of fast-logging.
- Record the code-location ID, LOC-ID, where l3_fast_log() is invoked.
This is conditionally enabled if env-var L3_LOC_ENABLED=1 is set.
Add new unit-test case and adjust existing use-case sample-programs to exercise these new interfaces.
Co-authored by Greg Law, who reworked l3.S to support this integration.
-----
Greg -- I squashed your assembly changes developed separately with mine, and added one minor clean-up commit. I'll fold that in , before pushing.
Meanwhile, there is still one more nagging issue. See [this comment](https://github.com/undoio/l3/pull/16/files#r1555049023) of mine. No rush to review this right now; you can get to it once your schedule …

Extend fast_log() assembly code to save-off LOC loc_t uint32_t value.

---

.github/workflows/build.yml
Makefile
test.sh

This commit refactors `test.sh` into individual build-and-test test-methods, each of which can be invoked by name from CI's build.yml script.
All existing CI jobs are now reworked as test-methods in test.sh
```
Linux-Vm:[678] $ ./test.sh --help
Usage: test.sh [--help | --list] [ --from-test <test-function-name> ] [test_all]
```
The basic change here is that `test.sh` now has this large collection of test-methods:
```
40 TestList=(
41            "test-build-and-run-unit-tests"
42
43            "test-build-C-samples"
44            "test-run-C-samples"
45
46            "test-build-Cpp-samples"
47            "test-run-Cpp-samples"
48
49            "test-build-Cc-samples"
50            "test-run-Cc-samples"
51
52            # These two should go back-to-back as a pair
53 …
```

[25] Refactor test.sh into test-methods that are invoked by CI's build.yml

---

.github/workflows/build.yml
Docs/build.md
l3_dump.py
test.sh
tests/pytests/l3_dump_parse_test.py

This commit does wholesale refactoring and modularization of the code in `l3_dump.py` into small methods which are individually testable.
- Modularize existing code into parsing methods using regular expressions
and captured-groups to extract individual fields from `.rodata` outputs.
E.g., add parse_rodata_start_offset(), parse_string_offsets() which
implement the parsing of the `readelf` output of .rodata section.
- Rework python script to lay-down flow into which support for Mac/OSX
variant of `readelf` output(s) can be easily folded-in.
- Add tests/pytests/l3_dump_parse_test.py - Drive unit-testing of parsing
logic thru new pytests.
- test.sh: Add test-pytests(), now also invoked thru CI build.yml
-------
**Motivation**  Actually -- this entire change-set started because I tried to …

Refactor l3_dump.py, add pytests. Pre-stage Mac/OSX support.

---

use-cases/single-file-C-program/test-main.c
use-cases/single-file-CC-program/test-main.cc
use-cases/single-file-Cpp-program/test-main.cpp

This commit refactors inline code in main() of 3 use-cases sample programs into individual functions:
- test_perf_slow_logging() and test_perf_fast_logging()
No other logic has changed. This refactoring is done to enable writing pytests, in future, to verify the outputs of logging.

[Test] Refactor use-cases sample programs into functions.

---

.github/workflows/build.yml
Docs/build.md
Makefile
include/l3.h
l3_dump.py
src/l3.c
tests/pytests/l3_dump_test.py

This commit adds a semi-minor overhaul of the build-and-test infrastructure to get the L3/LOC package, along with all newly added Pytest tests, running cleanly on Mac/OSX.
- Tested on macOS Monterey v12.1, and on macos-latest run in CI.
- On MacOSX, gcc is really clang, so with this commit, indirectly,  we also gain full support for clang. We need the `llvm-readelf` binary, which is a LLVM-provided gcc-equivalent binary to readelf.
- **build.yml**: New dependency on llvm-readelf binary that will be installed as part of LLVM install.
- Add new rules to build-and-test on MacOSX
- Install required software
- Main change is to update $PATH to include the path for
LLVM's llvm-readelf binary
- **Makefile**: We don't, yet, support fast-logging which needs assembly support. So, l3.S will only be …

[MacOSX] Port build infrastructure to run L3/LOC on Mac/OSX

---

.github/workflows/build.yml
Makefile
test.sh
use-cases/client-server-msgs-perf/ename.c.inc
use-cases/client-server-msgs-perf/error_functions.c
use-cases/client-server-msgs-perf/error_functions.h
use-cases/client-server-msgs-perf/get_num.h
use-cases/client-server-msgs-perf/svmsg_file.h
use-cases/client-server-msgs-perf/svmsg_file_client.c
use-cases/client-server-msgs-perf/svmsg_file_server.c
use-cases/client-server-msgs-perf/tlpi_hdr.h

This PR is a collection of multiple commits that incrementally build a client/server messaging program for use as a performance exerciser to measure overheads of L3/LOC diagnostic.
1. Initial version of client-server IPC msgs program sources.
2. Cleanup code-formatting in client-server IPC msgs program sources.
3. [Perf] Develop client-server comms. program to measure L3-logging overheads
-----
This commit adds the initial version of client-server messaging program sources as downloaded from Michael Kerrisk's reference book "The Linux Programming Interface".
Ref: https://man7.org/tlpi/code/online/all_files_by_chapter.html
Ch. 46: System V Message Queues.
Ref: git@github.com:bradfa/tlpi-dist.git
Required header files, along with the two main source files, svmsg_file_client.c and …

Develop client-server IPC msg Performance exerciser for L3-LOC overheads

---

.github/workflows/build.yml
Makefile
l3_dump.py
test.sh
use-cases/client-server-msgs-perf/svmsg_file_server.c

This PR packages two commits to integrate L3-logging invoked by the client-server performance test programs to now also invoke LOC-encoding as part of L3-Logging. The changes are mainly in `Makefile` with simple additions to `test.sh` and to `build.yml` to run these new changes thru CI.
1. [Perf] Makefile support to build client-server perf programs w/LOC encoding
2. [Perf] Makefile support to build client-server perf programs w/LOC-ELF
------
This commit implements Makefile rules to build the client-server programs such that L3-logging is performed with default LOC-encoding.
`./test.sh` : Add test-build-and-run-client-server-perf-test-l3_loc_eq_1 which is also invoked thru a call in CI build.yml
This test-case will run the client/server app and then will invoke the `l3_dump.py` to unpack …

[Perf] Extend Client-server perf tests to run with L3_LOC_ENABLED

---

Makefile
l3_dump.py
src/l3.c
tests/pytests/l3_dump_test.py

Rework L3 log-file header to identify type of logging done.
This commit overhauls the L3_LOG{} header struct at the head of a L3-logfile. Several changes are introduced to make the handling of log-files a bit more robust, and independent of environment
variables.
l3.c:
- Add enum l3_log_flags_t, to specify bit-flags to track type of logging in this log-file
- Rearrange L3_LOG{} to include `l3_log_flags_t  flags` field.
- Record the type of LOC-encoding used, which is determined as part of the build.
l3_dump.py:
- Add l3_unpack_loghdr() to figure out the type of LOC-encoding present, if any, in the log-entries.
- Rework identification of LOC-decode binary to use, without relying on environment variables.
If the Log header indicates that `LOC_DEFAULT` is in effect (i.e., the application was …

Formalize L3-log header. Add status flags. Remove dependence on env-variables.

---

l3_dump.py
test.sh
tests/pytests/l3_dump_parse_test.py
tests/pytests/l3_dump_test.py
tests/unit/l3_dump.py-test.c
use-cases/single-file-C-program/test-main.c
use-cases/single-file-CC-program/test-main.cc
use-cases/single-file-Cpp-program/test-main.cpp

This commit leverages an "old-style" Python print format to generate messages from the L3 log-file where 2 arguments are replaced in the users msg with embedded print-format specifiers.
We support most of the print specifiers Python supports:
- Massage the msg to replace '%p' -> '0x%x' as python does not support %p
- Fix %u, %lu and %llu handling. Add `test_fmtstr_replace_and_print()`
- Rework test-cases to cope with output messages with parameters replaced
- Fix all tests to work correctly with parameter substitution.
- Add `test_fmtstr_replace()`
A sample output from this change can be seen by running unit-tests to illustrate the benefit of this work:
$ make clean && CC=gcc LD=g++ make run-unit-tests
----
python3 l3_dump.py --log-file /tmp/l3.c-small-unit-test.dat --binary …

[Py] Extend L3-dump utility to generate C-printf()'ed output

---

l3_dump.py

Minor cleanup: Delete duplicate check `decode_loc_id == L3_LOC_UNSET` in this file, reporting a potential error condition. Bad code crept in due to previous merges.

l3_dump.py: fix merge-error.

---

samples/sample-c-appln/Makefile

This commit adds a descriptive prolog comment to the Makefile in the `samples/sample-c-appln`, to record, and acknowledge, the clone of the `lostella/SimpleMakefile` repo as a starting-point for this sample program sources.

sample-c-appln/Makefile: Acknowledge source of lostella/SimpleMakefile repo.

---

test.sh
use-cases/client-server-msgs-perf/svmsg_file_client.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit does some clean-up in the build-steps and test.sh execution steps for the client-server-perf-test exerciser sources:
`test.sh`:
- In `test-build-and-run-client-server-perf-test()`, invoke `l3_dump.py` script for the run with plain L3-logging enabled.
`svmsg_file_server.c`:
- Fix `char * loc_scheme` to be  "(no LOC)" for the case when LOC is not ON.
- Re-indent log call to be on one-line, to match-up line # more easily.
`svmsg_file_client.c`, `svmsg_file_server.c`:
- Consistently report 'default LOC' or 'LOC-ELF' encoding in msgs, depending on which of -D L3_LOC_ELF_ENABLED or -D L3_LOC_ENABLED was active during the build..

Fix bugs in client-server-perf-test msgs, and test-execution.

---

Makefile
tests/unit/size_str-test.c
use-cases/utils/size_str.c
use-cases/utils/size_str.h

This commit adds following size-/value to string with unit-specifier interfaces.
- Convert 'size' value (e.g., memory, space) to a string: 
```
char * size_to_str(char *outbuf, size_t outbuflen, size_t size);
char * size_to_fmtstr(char *outbuf, size_t outbuflen, const char *fmtstr, size_t size);
```
- Convert number-value value (e.g. # of requests) to a string:
```
char * value_to_str(char *outbuf, size_t outbuflen, size_t size);
char * value_to_fmtstr(char *outbuf, size_t outbuflen, const char *fmtstr, size_t size);
```
The size_to_str() implementation is extracted, and made stand-alone, out of the implementation done in the [SplinterDB repo](https://github.com/vmware/splinterdb). 
Further extended to add the `value_to_str()` interfaces.
- Add unit-test tests/unit/size_str-test.c
- Add …

[Util] Add size_to_str() and value_to_str() unit-conversion interfaces

---

Makefile
l3_dump.py
test.sh
use-cases/client-server-msgs-perf/svmsg_file.h
use-cases/client-server-msgs-perf/svmsg_file_client.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

The objective of this change is to demonstrate some realistic usages of L3-logging, which is currently done on the server-side of a simple client/server msg-send-recv application.
Rather than logging a plain 'Server msg' info, with some client details, we now also track the real-time / thread-CPU-time consumed on the server-side, for each client-op request. We only measure the block of code after msgrecv(), so don't track other scaffolding overheads.
The L3-logging call is now changed to also log this metric, which is a more natural use-case for this kind of logging API.
@gregthelaw - You can start reviewing this multi-part PR. I have reworked the implementation based on what we discussed yesterday and to prepare this change-set to be more inline with the `l3-perf-bm` proposal aired out …

[Perf] Track thread-CPU-time for each request on server-side.

---

include/l3.h
src/l3.c
tests/unit/l3_dump.py-test.c
use-cases/single-file-C-program/test-main.c
use-cases/single-file-CC-program/test-main.cc
use-cases/single-file-Cpp-program/test-main.cpp

This commit lays down the groundwork to re-engage u-benchmarking
programs to compare the overheads of L3-logging v/s, say, logging
via `printf()` or `write()` system call. 
In order to be able to do that, we first need to validate that the print format-specifiers in the 'msg' supplied to l3_log*() are consistent with the arguments supplied.
Currently, several of the use-case and sample programs are coded loosely w/o adhering to this requirement.
This commit implements the following changes:
- Slighly rearranges calling sequence of L3-logging APIs.
- Defines DEBUG-version of the caller-macros, which under an `else if (0)` [ dead-code block ] will evaluate to a call to `printf()`.
- This will trip-up compilation errors in debug-mode builds if any use-case of L3-logging apis have a message …

[L3] Rework logging APIs to invoke printf() for fmt-spec validation

---

include/l3.h
l3_dump.py
src/l3.c

This commit renames lower-level `l3__log_simple()` -> `l3_log_mmap()`, to indicate that the default L3-logging API is to an `mmap()`'ed log-file. There are no other functional changes introduced with this commit.

[L3] Rename l3__log_simple() -> l3_log_mmap()

---

include/l3.h
src/l3.c
tests/pytests/l3_dump_test.py
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit lays down some boilerplate code to add support for different logging schemes under L3. Introduce enum l3_log_t to specify different logging interfaces, mainly intended for use by micro-benchmarking utility programs. l3_log_init() becomes a shell around l3_init(), which remains the default interface to `init` a L3-logging system, on `mmap()`-ed files.
There are no other functional changes introduced with this commit.

[L3] Introduce l3_log_init() as a shell to call l3_init().

---

test.sh
use-cases/client-server-msgs-perf/svmsg_file_client.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit adds a new catch-all driver test-method, named `run-all-client-server-perf-tests`, to `test.sh`, which can be used to run through all client-server performance tests that are of interest.
This new method is not going to be run in CI as all it does is to execute other test-methods which _are_ executed in CI.
By default, all RPC-perf-tests are run with 5-concurrent clients, each sending 1000 messages to the server.
To make it easy to run dev-test performance benchmarks on dev-boxes, this test-method supports optional parameters:
- number-of-messages to be sent to the server by each client
- number-of-concurrent clients banging on the server
Usage:
```
./test.sh run-all-client-server-perf-tests [ <num-msgs> [ <num-clients> ] ]
```
$ ./test.sh run-all-client-server-perf-tests
$ …

[Test] Add run-all-client-server-perf-tests to test.sh

---

.github/workflows/build.yml
Makefile
test.sh
use-cases/utils/size_str.h

This commits comments out the `-Ofast` flag added to `Makefile`, which appears to show performance gains when client-server perf tests are run on Linux-VM.
Add new CI test-method, `test-run-all-client-server-perf-tests`, to run this exercise for 1 Million msgs, 1 client. 
Comment out this test-method, and it can be enabled by dev-engineers who wish to verify perf changes thru CI jobs.
`build.yml`: Add `test-run-all-client-server-perf-tests`
Initial performance benchmarking on Linux-VM for the client-server RPC-msg exerciser shows that:
- For single-client, overhead of L3-logging is ~10-13% (This drop needs further analysis.)
- For multiple clients, overhead of L3-logging is <3%,  which is what is expected.
-------------
The client-server performance test was executed before and after the …

[Perf] Use -Ofast for release and -Og for debug builds.

---

Makefile
test.sh
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit adds a new perf-test execution mode for the client-server performance u-benchmarking toolkit.
`L3_FASTLOG_ENABLED=1 make client-server-perf-test` will build the programs so that server will invoke l3_log_fast(), when needed.
test.sh: Refactoring.
- Extend test-build-and-run-client-server-perf-test to also execute a case when L3-fast-logging is invoked.
- Cleanup: Use local variables instead of hard-coded boolean 0/1s to specify if L3/LOC is enabled  / disabled.
svmsg_file_server.c: Invoke l3_log_fast() under `#if L3_FASTLOG_ENABLED`
which is supplied by the Makefile build-rules.
Build client/server programs to perform L3-fast logging:
```
$ make clean && CC=gcc LD=g++ L3_FASTLOG_ENABLED=1 make client-server-perf-test
```
**Units**: Throughput measured on server-side, in terms …

[Perf] Extend client-server perf test to invoke L3-fast logging

---

Makefile
samples/sample-c-appln/Makefile
test.sh

This commit implements couple of minor fixes to get the L3 sources and tests running cleanly on a privately-built Docker image. This is running Ubuntu 20.04.5 LTS/focal version.

Makefile and test.sh changes to build L3 on Docker images.

---

test.sh
use-cases/client-server-msgs-perf/svmsg_file.h
use-cases/client-server-msgs-perf/svmsg_file_client.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit simplifies the time-tracking fields for each client. Previously, we tried to track two different times:
1. CPU-clock-time for implementing the actual op
2. Real-time-clock-time for the whole process including the overheads of logging.
The idea was to measure (1) [ w/o logging ] and to track it as one of the arguments to the subsequent l3_log() call.
Another attempt made was to convert the cumulative [2] time to a throughput metric (num-ops / sec). But trying to mix these two time-tracking schemes, and jostle between `clock_gettime()` calls got confusing and needlessly unreliable.
This commit simplifies everything as follows.
Implement the code as:
```
a) clock_gettime() ◁----------------------------+
b) Do the n-operations in a forever-loop        |--> time measured for
c) …
```

[Perf] Revise 'time-consumed' tracking on server-side.

---

.github/workflows/build.yml
scripts/perf_report.py
test.sh
tests/pytests/perf_report_test.py
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit adds `scripts/perf_report.py`, which will generate a performance comparison summary report each time we run `./test.sh` to exercise the `run-all-client-server-perf-tests()` test-method.
- Change server-code slightly to generate a one-line summary in a canonical format. This is done under new `--perf-outfile` cmdline flag, and invoked by `./test.sh for run-all-client-server-perf-tests` method. (Manual execution of server program or executing other test-methods will -not- trigger this one-line summary output.)
- Add `scripts/perf_report.py` - parses the one-line summary generated in the file output under --perf-outfile flag, to generate the performance comparison report.
- Add `tests/pytests/perf_report_test.py`, to verify parsing logic.
- `test.sh`: Cleanup messages. Add …

[Perf] Generate performance comparison report from one-line metrics summary.

---

scripts/perf_report.py

This commit applies few PrettyTable() formatting directives to improve the readability and formatting of few columns in the perf-report.
Prior to this fix, the report would look like:
```
agurajada-Linux-Vm:[600] $ ./scripts/perf_report.py \
--file /tmp/test.sh.run-all-client-server-perf-tests.out
**** Performance comparison for NumClients=5, NumOps=5000000 (5 Million) ****
+--------------------------+-------------------+----------+-------------------+----------+
|         Run-Type         | Server throughput | S:%-Drop | Client throughput | C:%-Drop |
+--------------------------+-------------------+----------+-------------------+----------+
|  Baseline - No logging   | ~100.14 K ops/sec |   0.0    |  ~22.91 K ops/sec |   0.0    |
|   L3-logging (no LOC)    |  ~99.77 K ops/sec |  -0.36 …
```

[Perf] Enhance formatting of fields in perf report

---

test.sh
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit does some low-impact cleanup of client-server perf-tests
- `test.sh`: Currently, these tests were restricted for use on Mac/OSX. However, there are compilation errors in client-server sources on this platform. Rework the restrictions such that all test-methods do perform the build (`make`) step, but skip the execution step. This caught few compilation errors that show up only on Mac/OSX.
-  Delete obsolete test-execution code from test.sh, replaced by named test-methods.
- Fix l3_log() msgs to say 'Counter' rather than 'Elapsed time' as, due to changes done under SHA 2d6b9d6, we are no longer tracking and logging the elapsed-time of each msg implemented.

Cleanup: Update msgs to report 'counter'. Rework Mac/OSX restrictions.

---

Makefile
include/l3.h
src/l3.c
test.sh
use-cases/client-server-msgs-perf/svmsg_file_client.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit adds support for `L3_LOGT_FPRINTF=1 make client-server-perf-test` to build client-server perf-tests to log using the `fprintf()` system call.
Makefile and #if'def-ed code is added to support fprintf() logging. `l3_log_fprintf()` defined as static inline to avoid fn-call overhead. 
test.sh - Add "fprintf" support to existing test-method.
Fix seg-fault running fprintf() logging in debug mode.

[Perf] Support L3_LOGT_FPRINTF -> l3_log_fprintf() for benchmarking.

---

test.sh

This commit externalizes existing test-code into standalone test-build-and-run-client-server-perf-test-fprintf() test-method. This can now be executed as its own target for quick-check of perf using fprintf()-logging.

[Perf] test.sh: Refactor into standalone fprintf() logging test method

---

Makefile
include/l3.h
src/l3.c
test.sh
tests/unit/l3-fprintf-perf-test.c
tests/unit/l3-perf-test.h
tests/unit/l3-write-perf-test.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit adds support for `L3_LOGT_WRITE=1 make client-server-perf-test` to build client-server perf-tests to log using write() system call.
- Makefile and #if'def-ed code is added to support write() logging.
- test.sh - Add "write" logging-support to existing test-method.
-----
This commit adds couple of new unit-tests to do standalone micro-benchmarking of the performance of l3_log_fprintf(),
vs l3_log_write() interfaces.
- `make run-unit-tests` will automatically invoke these new tests.
- To resolve usefulness of `write()` v/s writing out a formatted a message, this perf unit-test provides an alternate implementation of `write_msg()` interface thru `l3_log()`.
Details in the descriptions below.

[Perf] Support L3_LOGT_WRITE -> l3_log_write() for benchmarking.

---

include/l3.h
src/l3.c
use-cases/client-server-msgs-perf/svmsg_file_server.c

Change server to deinit() L3's logging system, so contents are  reliably flushed to disk. Suppress call to syncfs() on Mac/OSX.

[L3] Add l3_log_deinit(): Close file opened.

---

.github/workflows/build.yml
Makefile
src/l3.c
test.sh
use-cases/client-server-msgs-perf/ename.c.inc
use-cases/client-server-msgs-perf/svmsg_file_server.c
use-cases/spdlog-Cpp-program/test-main.cpp
use-cases/utils/size_str.c

This commit introduces a very basic spdlog-tutorial program.
- Add use-cases/spdlog-Cpp-program/test-main.cpp
- Makefile:
- Add build-rules to build this source on Linux, Mac/OSX and Docker
- New target spdlog-cpp-program; needs CC=g++ LD=g++
- Handle env-var RUN_ON_CI, to fix SPD_INCLUDE_ROOT path that works on CI-Mac/OSX machines, as installed by `brew install`
- test.sh:
- Add test-build-and-run-spdlog-sample
- CI/build.yml:
- Install required pre-requisite packages, spdlog and fmt
- Customize install env for Linux & Mac/OSX
- Provide special-invocation env-var: RUN_ON_CI=1
------
This commits injects spdlog-logging into the existing client-server performance u-benchmarking programs.
Usage:
```
make clean && CC=g++ LD=g++ L3_ENABLED=0 L3_LOGT_SPDLOG=1 make client-server-perf-test  # …
```

[Spdlog] Add spdlog sample program, Makefile and CI build.yml rules

---

use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit cleans up tracing field `cumu_time_ns`, which is no longer being tracked on the server-side. Cleanup stray messages left-over reporting throughput=0 value. Other message cleanup. No other logic changes done to actual perf u-benchmarking metrics.

Delete client_info.cumu_time_ns field; not being tracked.

---

test.sh

This commit makes the optional parameters to all test-methods, named test-build-and-run-client-server-perf-test*, consistent, so that arg-parsing remains symmetric. New usage is:
```
$ test.sh run-all-client-server-perf-tests [ server-clock-ID [ num-msgs [ num-clients ] ] ] 
$ test.sh test-build-and-run-client-server-perf-test [ server-clock-ID [ num-msgs ] ]
```
and so on. This applies to all these test-methods:
- test-build-and-run-client-server-perf-test
- test-build-and-run-client-server-perf-test-fprintf
- test-build-and-run-client-server-perf-test-write
- test-build-and-run-client-server-perf-test-l3_loc_eq_1
- test-build-and-run-client-server-perf-test-l3_loc_eq_2
- test-build-and-run-client-server-perf-test-spdlog

[Test] Make order of args to test-build-and-run-client-server-perf-test consistent.

---

test.sh

Fix the calls to individual perf test-methods from `run-all-client-server-perf-tests()`. 
The interface for all these perf-test methods has been changed to receive "server clock-id" string arg as 1st param. Changes in previous commit has broken the calling sequence, and this commit fixes it.

Fix regr from previous commit. Affects perf test-runs.

---

.github/workflows/build.yml
test.sh

This commit lays down the groundwork so that, in future, we can execute the client-server perf tests with different number of server-threads.
This commit refactors, renames and modularizes client-server perf-test methods in test.sh . With this commit, we continue to run tests with a single thread, preparing the ground to leverage the `--num-server-threads <n>` argument added to the server-program.
- Wholesale shortening and renaming of perf-test methods Made test-methods granular, so that each can be independently exercised and verified by dev-tests.
- Break-out test-build-and-run-client-server-perf-test() into: 
- test-build-and-run-csperf-baseline() 
- test-build-and-run-csperf-l3-log() 
- test-build-and-run-csperf-fast-log-no-LOC()
- Break-out spdlog test-methods into: 
- …

[Perf] Refactor perf-test methods to run with multiple server-threads.

---

src/l3.c

In large-volume performance benchmarking we end up generating huge log files, `/tmp/l3.c-server-test.dat`, when client-server programs are built with `L3_LOGT_WRITE=1`. For write()-logging, we append log-entries to the same file, which eventually busts-up against the disk space.
This fix corrects this by opening the file
with: (O_RDWR | O_CREAT | O_APPEND)
rather than: (O_RDWR | O_CREAT | O_TRUNC)
flags. For performance benchmarking, there is no need to retain older log-entries.

Change open() flags from O_APPEND -> O_TRUNC for write() logging.

---

scripts/ipcrm.sh
scripts/perf_report.py
test.sh
tests/pytests/perf_report_test.py
use-cases/client-server-msgs-perf/svmsg_file_server.c

This commit supports use of `--num-server-threads n` arg (to the `svmsg_file_server program`) with n > 1 threads. This will invoke n-server-side threads, to receive and process the messages received from the client program.
The objective is to measure any perf-impact due to concurrent logging of messages performed by multiple server threads.
- svmsg_file_server.c:
- Prev commit already support notion of num_threads. With this change, we are now able to execute tests using more than 1 server-thread.
- Use atomic int support to manage updates to # client-connections globals. Adjust code to work with both C & C++ compilation.
Fortunately, due to the simplistic client-specific way messages are received & processed, we needed no new synchronization methods between server threads. Atomic incr / …

[Perf] Support multi-threaded server execution. Update test.sh perf methods.

---

l3.S
src/l3.c

An optimisation for single-threaded; gets the overhead of a `l3_log_fast()` down to 2ns on my laptop.
Also fixes the bodge I made for accessing the tid in TLS in l3.S.

Log fast single threaded improves

---

scripts/perf_report.py
test.sh
tests/pytests/perf_report_test.py

In previous performance test-runs, we were able to only run one iteration of the client-server program for each run-type, test-parameter. We were seeing some fluctuations and unexpected results in the comparison report.
This commit enhances the testing framework to:
a) Run 1 or more iterations of the client/server program
b) Extend the Python perf-comparison report generator to work
with another source of input metrics-line(s).
c) Comparison report generated using median value of the
relevant metric across the n-iterations.
Note: (b) was needed as runs on AWS were aborted midway and had to be partially re-run. We add Python parsing logic to extract out and massage metrics from "Summary: " output lines, that the server program emits to `stdout`.
- To run multiple iterations, use env-var …

[Perf] Enhance test.sh and perf_report.py to support multiple iterations.

---

.github/workflows/build.yml
Makefile
test.sh
use-cases/source-location-Cpp-program/source-location-log.cpp
use-cases/source-location-Cpp-program/source-location-main-C++20.cpp
use-cases/source-location-Cpp-program/source-location-minion.cpp
use-cases/source-location-Cpp-program/source-location-utils.cpp
use-cases/source-location-Cpp-program/source-location.h

This commit adds the initial version of a sample program to exercise C++20's feature of `std::source_location{}` object.
Enhanced source cp'ed from:
https://en.cppreference.com/w/cpp/utility/source_location
- Add source-location.h and  minion.cpp
- Minor refactoring of messasges.
- log() returns source_location of callee. Print that in caller.
- Refactor: Add pr_source_location().
This commit brings-in source-location-minion.cpp where another caller to LOG() macro is added. LOG() is defined in source-location.h as a caller-macro, supplying `location` arg.
- Working version of Makefile: make source-location-cpp20-program
- make target works on Linux-VM, and also on Mac/OSX in CI.
- Add test-build-and-run-source-location-cpp20-sample() test-method.
- Distribute helper fns to log.cpp and …

Initial C++20 source_location{} use-case program, make source-location-cpp20-program.

---

Makefile

Suppress info messages reporting the state of various symbols built as part of Make-processing. These are printed for debugging and clutter up the BUILD_VERBOSE=1 output. Move them to under BUILD_VERBOSE=2 flag.
Cleanup `help` output. We no longer need to specify `L3_LOC_ENABLED=1` to run `make run-c-tests` target. The L3-dump script figures out if any LOC-encoding was in effect by deciphering the log-header.

Makefile Cleanup: Print debug info for BUILD_VERBOSE=2

---

Makefile

This commit fixes minor errors in `Makefile` specifying the `SPD_INCLUDE_ROOT`, and adds missing `SPD_LIBS_PATH`, required for buiding the sample spdlog program on personal Mac. Build goes thru further, but eventally still fails.

Fix Makefile to build spdlog sample prog on personal Mac/OSX

---

.github/workflows/build.yml
Makefile
test.sh
tests/perf/Makefile
tests/perf/mt_ubench_l3.cpp
tests/perf/mt_ubench_spdlog.cpp

This commit integrates the micro performance benchmark source  into the top-level Makefile, adding folllowing new targets:
- To build-and-run L3/spdlog performance micro-benchmarks
`make clean && CXX=g++ LD=g++ make all-mt-ubench && make run-mt-ubench`
- Makefile: Make required changes to build and run these new micro perf benchmarks
mt_ubench_spdlog.cpp, mt_ubench_l3.cpp:
Cleanup. Parametrize perf u-bm configs.
-Add tests execution to test.sh and CI build.yml

[Perf] Integrate micro perf-bm sources into Makefile targets

---

l3.S
src/l3.c

My previous attempt to fix usage of TLS wasn't right because child threads would not have their TLS thread initialised. This PR fixes that by zero-initialising the TLS thread, and checking it from every call.

More fixes to use of TLS from assembly code.

---

.github/workflows/build.yml
Makefile
test.sh
tests/perf/Makefile
tests/perf/mt_ubench_l3.cpp
tests/perf/mt_ubench_spdlog.cpp

Spawn 10 threads, each does a million logs.
We have two: one for L3 and one for spdlog.
For this test, L3 is over 20x faster than spdlog.
```
$ time ./spdlog.exe 
real    0m18.050s
user    0m29.033s
sys     1m17.579s
$
$
$ time ./l3.exe 
real    0m0.814s
user    0m6.623s
sys     0m0.028s
$
```

Add some multi-threaded micro-benchmarks.
